{% set version = '0.9.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-kableextra
  version: {{ version|replace("-", "_") }}

source:
  fn: kableExtra_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/kableExtra_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/kableExtra/kableExtra_{{ version }}.tar.gz
  sha256: 6e3dac92dc064c246a6f102f91ae7a8324afab9d6307632fdee77d3b1e15431c

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, magick, formattable, dplyr
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base=3.4.1
    - r-htmltools
    - r-knitr >=1.16
    - r-magrittr
    - r-readr
    - r-rmarkdown >=1.6.0
    - r-rstudioapi
    - r-rvest
    - r-scales
    - r-stringr >=1.0
    - r-viridislite
    - r-xml2 >=1.1.1

  run:
    - r-base=3.4.1
    - r-htmltools
    - r-knitr >=1.16
    - r-magrittr
    - r-readr
    - r-rmarkdown >=1.6.0
    - r-rstudioapi
    - r-rvest
    - r-scales
    - r-stringr >=1.0
    - r-viridislite
    - r-xml2 >=1.1.1

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('kableExtra')"           # [not win]
    - "\"%R%\" -e \"library('kableExtra')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://haozhu233.github.io/kableExtra/, https://github.com/haozhu233/kableExtra
  license: MIT + file LICENSE
  summary: 'Build complex HTML or ''LaTeX'' tables using ''kable()'' from ''knitr''  and the
    piping syntax from ''magrittr''. Function ''kable()'' is a light weight  table generator
    coming from ''knitr''. This package simplifies the way to  manipulate the HTML or
    ''LaTeX'' codes generated by ''kable()'' and allows  users to construct complex
    tables and customize styles using a readable  syntax. '

  license_family: MIT

# The original CRAN metadata for this package was:

# Package: kableExtra
# Type: Package
# Title: Construct Complex Table with 'kable' and Pipe Syntax
# Version: 0.9.0
# Authors@R: c( person('Hao', 'Zhu', email = 'haozhu233@gmail.com', role = c('aut', 'cre'), comment = c(ORCID = '0000-0002-3386-6076')), person('Thomas', 'Travison', role = 'ctb'), person('Timothy', 'Tsai', role = 'ctb'), person('Will', 'Beasley', email = 'wibeasley@hotmail.com', role = 'ctb'), person('Yihui', 'Xie', email = 'xie@yihui.name', role = 'ctb'), person('GuangChuang', 'Yu', email = 'guangchuangyu@gmail.com', role = 'ctb'), person('Stephane', 'Laurent', role = 'ctb'), person('Rob', 'Shepherd', role = 'ctb'), person('Yoni', 'Sidi', role = 'ctb'),  person('Brian', 'Salzer', role = 'ctb'), person('George', 'Gui', role = 'ctb'), person('Yeliang', 'Fan', role = 'ctb') )
# Description: Build complex HTML or 'LaTeX' tables using 'kable()' from 'knitr'  and the piping syntax from 'magrittr'. Function 'kable()' is a light weight  table generator coming from 'knitr'. This package simplifies the way to  manipulate the HTML or 'LaTeX' codes generated by 'kable()' and allows  users to construct complex tables and customize styles using a readable  syntax.
# License: MIT + file LICENSE
# LazyData: TRUE
# URL: http://haozhu233.github.io/kableExtra/, https://github.com/haozhu233/kableExtra
# BugReports: https://github.com/haozhu233/kableExtra/issues
# Depends: R (>= 3.1.0)
# Imports: knitr (>= 1.16), magrittr, stringr (>= 1.0), xml2 (>= 1.1.1), rvest, rmarkdown (>= 1.6.0), readr, scales, viridisLite, stats, grDevices, htmltools, rstudioapi
# Suggests: testthat, magick, formattable, dplyr
# VignetteBuilder: knitr
# Encoding: UTF-8
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-05-21 05:00:29 UTC; haozhu
# Author: Hao Zhu [aut, cre] (<https://orcid.org/0000-0002-3386-6076>), Thomas Travison [ctb], Timothy Tsai [ctb], Will Beasley [ctb], Yihui Xie [ctb], GuangChuang Yu [ctb], Stephane Laurent [ctb], Rob Shepherd [ctb], Yoni Sidi [ctb], Brian Salzer [ctb], George Gui [ctb], Yeliang Fan [ctb]
# Maintainer: Hao Zhu <haozhu233@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-05-21 07:22:58

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
