{% set version = '0.0.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rock
  version: {{ version|replace("-", "_") }}

source:

  git_url: https://github.com/umccr/rock
  git_tag: 0.0.1

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: covr, knitr, rmarkdown, testthat,
requirements:
  build:
    - {{posix}}filesystem        # [win]
    - {{posix}}git
    - {{posix}}zip               # [win]

  host:
    - r-base=3.4.1
    - bioconductor-genomicranges
    - bioconductor-omiccircos
    - r-dplyr
    - r-ggplot2
    - r-glue
    - r-pebbles
    - r-purrr
    - r-readr
    - r-rlang >=0.1.2
    - r-scales
    - r-tibble
    - r-tidyr
    - r-vcfr

  run:
    - r-base=3.4.1
    - bioconductor-genomicranges
    - bioconductor-omiccircos
    - r-dplyr
    - r-ggplot2
    - r-glue
    - r-pebbles
    - r-purrr
    - r-readr
    - r-rlang >=0.1.2
    - r-scales
    - r-tibble
    - r-tidyr
    - r-vcfr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rock')"           # [not win]
    - "\"%R%\" -e \"library('rock')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/umccr/rock
  license: MIT + file LICENSE
  summary: Contains functions for bioinformatic analyses.
  license_family: MIT

# The original CRAN metadata for this package was:

# Package: rock
# Version: 0.0.1
# Title: Rocking R at UMCCR
# Description: Contains functions for bioinformatic analyses.
# Authors@R: person("Peter", "Diakumis", email = "peterdiakumis@gmail.com", role = c("aut", "cre"))
# URL: https://github.com/umccr/rock
# BugReports: https://github.com/umccr/rock/issues
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: true
# ByteCompile: true
# Remotes: github::umccr/pebbles
# Depends: R (>= 2.10)
# Imports: dplyr, GenomicRanges, ggplot2, glue, OmicCircos, pebbles, purrr, readr, rlang (>= 0.1.2), scales, tibble, tidyr, vcfR
# Roxygen: list(markdown = TRUE)
# RoxygenNote: 6.1.0
# Suggests: covr, knitr, rmarkdown, testthat,
# VignetteBuilder: knitr

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
