{% set version = '2.1.4' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sunburstr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sunburstR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sunburstR/sunburstR_{{ version }}.tar.gz
  sha256: 816095a8bb2a87210e5bdc90b925894307aebd204b7462b61a977e4cfd12d0ee

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: jsonlite, knitr, markdown, pipeR, testthat, tidyr (>= 0.7.0), rmarkdown
requirements:
  build:
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-d3r >=0.6.9
    - r-dplyr
    - r-htmltools
    - r-htmlwidgets

  run:
    - r-base
    - r-d3r >=0.6.9
    - r-dplyr
    - r-htmltools
    - r-htmlwidgets

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('sunburstR')"           # [not win]
    - "\"%R%\" -e \"library('sunburstR')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/timelyportfolio/sunburstR

  license: MIT
  summary: Make interactive 'd3.js' sequence sunburst diagrams in R with the convenience and
    infrastructure of an 'htmlwidget'.

  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

# The original CRAN metadata for this package was:

# Package: sunburstR
# Type: Package
# Title: Sunburst 'Htmlwidget'
# Version: 2.1.4
# Date: 2020-07-06
# Authors@R: c( person( "Mike", "Bostock" , role = c("aut", "cph") , comment = "d3.js library, http://d3js.org" ), person( "Kerry", "Rodden" , role = c("aut", "cph") , comment = "sequences library in htmlwidgets/lib, https://gist.github.com/kerryrodden/7090426" ), person( "Kevin", "Warne" , role = c("aut", "cph") , comment = "d2b sunburst library in htmlwidgets/lib, https://github.com/d2bjs/d2b" ), person( "Kent", "Russell" , role = c("aut", "cre") , comment = "R interface" , email = "kent.russell@timelyportfolio.com" ), person( "Florian", "Breitwieser" , role = c("ctb") , comment = "R interface" ), person( "CJ", "Yetman" , role = c("ctb") , comment = c("R interface", ORCID = "0000-0001-5099-9500") , email = "cj@cjyetman.com" ) )
# Maintainer: Kent Russell <kent.russell@timelyportfolio.com>
# URL: https://github.com/timelyportfolio/sunburstR
# BugReports: https://github.com/timelyportfolio/sunburstR/issues
# Description: Make interactive 'd3.js' sequence sunburst diagrams in R with the convenience and infrastructure of an 'htmlwidget'.
# License: MIT + file LICENSE
# LazyData: TRUE
# Imports: d3r (>= 0.6.9), dplyr, htmlwidgets, htmltools
# Suggests: jsonlite, knitr, markdown, pipeR, testthat, tidyr (>= 0.7.0), rmarkdown
# Enhances: treemap
# RoxygenNote: 7.1.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2020-07-06 19:24:54 UTC; kentr
# Author: Mike Bostock [aut, cph] (d3.js library, http://d3js.org), Kerry Rodden [aut, cph] (sequences library in htmlwidgets/lib, https://gist.github.com/kerryrodden/7090426), Kevin Warne [aut, cph] (d2b sunburst library in htmlwidgets/lib, https://github.com/d2bjs/d2b), Kent Russell [aut, cre] (R interface), Florian Breitwieser [ctb] (R interface), CJ Yetman [ctb] (R interface, <https://orcid.org/0000-0001-5099-9500>)
# Repository: CRAN
# Date/Publication: 2020-07-06 22:30:03 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
