{% set version = '0.3.3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-configr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/configr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/configr/configr_{{ version }}.tar.gz
  sha256: a283635e688be27f326c98adc1229087c07c1a3377a194f6aa660a283501ca21

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, knitr, rmarkdown, prettydoc
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-rcpptoml >=0.1.3
    - r-glue
    - r-ini >=0.2
    - r-jsonlite >=1.2
    - r-stringr >=1.2.0
    - r-yaml >=2.1.3

  run:
    - r-base
    - r-rcpptoml >=0.1.3
    - r-glue
    - r-ini >=0.2
    - r-jsonlite >=1.2
    - r-stringr >=1.2.0
    - r-yaml >=2.1.3

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('configr')"           # [not win]
    - "\"%R%\" -e \"library('configr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/Miachol/configr
  license: MIT + file LICENSE
  summary: ' Implements the JSON, INI, YAML and TOML parser for R setting and writing of configuration
    file. The functionality of this package is similar to that of package ''config''. '

  license_family: MIT

# The original CRAN metadata for this package was:

# Package: configr
# Type: Package
# Title: An Implementation of Parsing and Writing Configuration File (JSON/INI/YAML/TOML)
# Version: 0.3.3
# Authors@R: person("Jianfeng", "Li", email = "lee_jianfeng@sjtu.edu.cn", role = c("aut", "cre"), comment = c(ORCID = "0000-0003-2349-208X"))
# Description:  Implements the JSON, INI, YAML and TOML parser for R setting and writing of configuration file. The functionality of this package is similar to that of package 'config'.
# Depends: R (>= 3.3.0)
# URL: https://github.com/Miachol/configr
# BugReports: https://github.com/Miachol/configr/issues
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: true
# Imports: jsonlite (>= 1.2), ini (>= 0.2), yaml (>= 2.1.3), RcppTOML (>= 0.1.3), stringr (>= 1.2.0), utils, glue
# RoxygenNote: 6.0.1
# Suggests: testthat, knitr, rmarkdown, prettydoc
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2018-06-22 14:19:51 UTC; ljf
# Author: Jianfeng Li [aut, cre] (<https://orcid.org/0000-0003-2349-208X>)
# Maintainer: Jianfeng Li <lee_jianfeng@sjtu.edu.cn>
# Repository: CRAN
# Date/Publication: 2018-06-22 15:12:57 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
