{% set version = '0.4.4' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-nnlm
  version: {{ version|replace("-", "_") }}

source:
  git_url: https://github.com/linxihui/NNLM
  git_tag: 0.4.4

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppprogress

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppprogress

test:
  commands:
    - $R -e "library('NNLM')"           # [not win]
    - "\"%R%\" -e \"library('NNLM')\""  # [win]

about:
  home: https://github.com/linxihui/NNLM
  license: BSD_2_clause + file LICENSE
  summary: This is a package for Non-Negative Linear Models (NNLM). It implements
    fast sequential coordinate descent algorithms for non-negative linear regression
    and non-negative matrix factorization (NMF). It supports mean square error and
    Kullback-Leibler divergence loss. Many other features are also implemented,
    including missing value imputation, domain knowledge integration,
    designable W and H matrices and multiple forms of regularizations.
  license_family: BSD
