{% set version = '0.2.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pctgcdata
  version: {{ version|replace("-", "_") }}

source:

  git_url: https://github.com/mskcc/pctGCdata
  git_tag: v0.2.0

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}filesystem        # [win]
    - {{posix}}git
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('pctGCdata')"           # [not win]
    - "\"%R%\" -e \"library('pctGCdata')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/mskcc/pctGCdata
  license: GPL (>= 2)
  summary: Provides GC percentage of a 1 kilobase window at a genomic position for different
    builds of human and mouse genomes.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: pctGCdata
# Type: Package
# Title: Datasets of GC percentages for human and mouse genomes
# Version: 0.2.0
# Date: 2016-09-21
# Depends: R (>= 3.0.0)
# Author: Venkatraman E. Seshan, Nicholas D. Socci
# Maintainer: Venkatraman E. Seshan <seshanv@mskcc.org>
# Description: Provides GC percentage of a 1 kilobase window at a genomic position for different builds of human and mouse genomes.
# License: GPL (>= 2)
# LazyData: yes
# NeedsCompilation: no

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
