{% set version = '2.00' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-chord
  version: {{ version|replace("-", "_") }}

source:

  git_url: https://github.com/UMCUGenetics/CHORD
  git_tag: 2.00

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: doMC, Boruta
requirements:
  build:
    - {{ posix }}filesystem        # [win]
    - {{ posix }}git
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-mutsigextractor
    - r-randomforest

  run:
    - r-base
    - r-mutsigextractor
    - r-randomforest

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('CHORD')"           # [not win]
    - "\"%R%\" -e \"library('CHORD')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/UMCUGenetics/CHORD
  license: MIT
  summary: CHORD is a random forest model that uses the relative counts of somatic mutation contexts
    to predict homologous recombination deficiency (HRD). The primary contexts used
    by CHORD are deletions with flanking microhomology and 1-100kb structural duplications.
    Additionally, 1-100kb structural duplications are used to distinguish BRCA1-type
    HRD from BRCA2-type HRD.

  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'

# The original CRAN metadata for this package was:

# Package: CHORD
# Type: Package
# Title: Classifier of Homologous Recombination Deficiency
# Version: 2.00
# Author: Luan N. Nguyen
# Maintainer: Luan N. Nguyen <n.l.nguyen-2@umcutrecht.nl>
# Description: CHORD is a random forest model that uses the relative counts of somatic mutation contexts to predict homologous recombination deficiency (HRD). The primary contexts used by CHORD are deletions with flanking microhomology and 1-100kb structural duplications. Additionally, 1-100kb structural duplications are used to distinguish BRCA1-type HRD from BRCA2-type HRD.
# License: MIT
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.1.0
# biocViews:
# Remotes: github::UMCUGenetics/mutSigExtractor
# Imports: mutSigExtractor, randomForest
# Suggests: doMC, Boruta

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
