{% set version = '0.3.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-googlesheets
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/googlesheets_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/googlesheets/googlesheets_{{ version }}.tar.gz
  sha256: 685b9edf16f05103c751f70d7856de7c3f209c9795ab9a7a9f5c1cedbb3d0087

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: covr, ggplot2, knitr, rmarkdown, rprojroot, testthat (>= 1.0.0)
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-cellranger >=1.0.0
    - r-dplyr >=0.4.2
    - r-httr >=1.1.0
    - r-jsonlite
    - r-purrr
    - r-readr >=0.2.2
    - r-stringr
    - r-tibble
    - r-tidyr
    - r-xml2 >=1.0.0

  run:
    - r-base
    - r-cellranger >=1.0.0
    - r-dplyr >=0.4.2
    - r-httr >=1.1.0
    - r-jsonlite
    - r-purrr
    - r-readr >=0.2.2
    - r-stringr
    - r-tibble
    - r-tidyr
    - r-xml2 >=1.0.0

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('googlesheets')"           # [not win]
    - "\"%R%\" -e \"library('googlesheets')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/jennybc/googlesheets
  license: MIT + file LICENSE
  summary: Interact with Google Sheets from R.
  license_family: MIT

# The original CRAN metadata for this package was:

# Package: googlesheets
# Title: Manage Google Spreadsheets from R
# Version: 0.3.0
# Authors@R: c( person("Jennifer", "Bryan", , "jenny@rstudio.com", c("aut", "cre")), person("Joanna", "Zhao", , "joanna.zhao@alumni.ubc.ca", role = "aut") )
# Description: Interact with Google Sheets from R.
# License: MIT + file LICENSE
# URL: https://github.com/jennybc/googlesheets
# BugReports: https://github.com/jennybc/googlesheets/issues
# Depends: R (>= 3.2.0)
# Imports: cellranger (>= 1.0.0), dplyr (>= 0.4.2), httr (>= 1.1.0), jsonlite, purrr, readr (>= 0.2.2), stats, stringr, tibble, tidyr, utils, xml2 (>= 1.0.0)
# Suggests: covr, ggplot2, knitr, rmarkdown, rprojroot, testthat (>= 1.0.0)
# VignetteBuilder: knitr
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.0.1.9000
# NeedsCompilation: no
# Packaged: 2018-06-29 03:24:12 UTC; jenny
# Author: Jennifer Bryan [aut, cre], Joanna Zhao [aut]
# Maintainer: Jennifer Bryan <jenny@rstudio.com>
# Repository: CRAN
# Date/Publication: 2018-06-29 04:38:09 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
